---
version: '3.1'

services:
  mongodb:
    image: mongo:3.6.7-jessie
    ports:
      - "27017:27017"

  mongo-seed:
    build: databases/mongo-seed
    links:
      - mongodb

  maria:
    image: mariadb:10.3.9
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "super duper password"
      MYSQL_DATABASE: "hapivue"
    volumes:
      - ./databases/maria/users.sql:/docker-entrypoint-initdb.d/01-users.sql
