---
version: '3.1'
services:
  mongodb:
    image: mongo:3.6.7-jessie
    ports:
      - "27017:27017"

  mongo-seed:
    build: databases/mongo-seed
    environment:
      MONGO_URI: "mongodb://mongodb/hapivue"
      CSV_FILE: "data.csv"

  maria:
    image: mariadb:10.3.9
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "super duper password"
      MYSQL_DATABASE: "hapivue"
    volumes:
      - ./databases/maria/db_users.sql:/docker-entrypoint-initdb.d/01-users.sql
      - ./databases/maria/users.sql:/docker-entrypoint-initdb.d/02-tables.sql
      - ./databases/maria/my.cnf:/etc/mysql/conf.d/custom.cnf
  register:
    build: microservices/register
    links:
      - maria
    ports:
      - "5000:5000"
    environment:
      SQL_URI: "\
        mysql+pymysql://\
        ms_writer:\
        Hjpvv1x22ci_-SJWtyZNhrFDkRK0cSNrwczx7fSkME4c2xOTXDmJfwFOpQ5w\
        @maria/hapivue\
        "
  connection:
    build: microservices/connection
    ports:
      - "5001:5001"
    environment:
      SQL_URI: "\
        mysql+pymysql://\
        ms_writer:\
        Hjpvv1x22ci_-SJWtyZNhrFDkRK0cSNrwczx7fSkME4c2xOTXDmJfwFOpQ5w\
        @maria/hapivue\
        "
  token:
    build: microservices/token
    ports:
      - "5002:5002"
    environment:

      SQL_URI: "\
        mysql+pymysql://\
        ms_reader:\
        Zevflhy0PRB6ZbD8P0ubeBzH81lXRY7D5IrnQH96pjr7jjeJKD5W9LrvV9P0\
        @maria/hapivue\
        "
  activate:
    build: microservices/activate
    ports:
      - "5003:5003"
    environment:
      SQL_URI: "\
        mysql+pymysql://\
        ms_writer:\
        Hjpvv1x22ci_-SJWtyZNhrFDkRK0cSNrwczx7fSkME4c2xOTXDmJfwFOpQ5w\
        @maria/hapivue\
        "
  search:
    build: microservices/search
    ports:
      - "5004:5004"
    environment:
      MONGO_URI: "mongodb://mongodb/hapivue"
  delete:
    build: microservices/delete
    ports:
      - "5005:5005"
    environment:
      SQL_URI: "\
        mysql+pymysql://\
        ms_writer:\
        Hjpvv1x22ci_-SJWtyZNhrFDkRK0cSNrwczx7fSkME4c2xOTXDmJfwFOpQ5w\
        @maria/hapivue\
        "
