CREATE USER 'ms_reader'@'%' IDENTIFIED BY 'Zevflhy0PRB6ZbD8P0ubeBzH81lXRY7D5IrnQH96pjr7jjeJKD5W9LrvV9P0';
GRANT SELECT ON hapivue.* TO 'ms_reader'@'%' IDENTIFIED BY 'Zevflhy0PRB6ZbD8P0ubeBzH81lXRY7D5IrnQH96pjr7jjeJKD5W9LrvV9P0';
CREATE USER 'ms_writer'@'%' IDENTIFIED BY 'Hjpvv1x22ci_-SJWtyZNhrFDkRK0cSNrwczx7fSkME4c2xOTXDmJfwFOpQ5w';
GRANT SELECT, INSERT, UPDATE ON hapivue.* TO 'ms_writer'@'%' IDENTIFIED BY 'Hjpvv1x22ci_-SJWtyZNhrFDkRK0cSNrwczx7fSkME4c2xOTXDmJfwFOpQ5w';
